# Filterbank config
filterbank:
  enc_num_ch: 1
  dec_num_ch: 1
  n_filters: 64
  kernel_size: 16
  stride: 8
# Network config
masknet:
  in_chan: 64
  out_chan: 64
  ff_hid: 256
  ff_activation: "relu"
  norm_type: "gLN"
  chunk_size: 100
  hop_size: 50
  n_repeats: 2
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
# Training config
training:
  epochs: 60
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
  pretrained: /data/projects/swat/users/eladco/models/audio/DPTNet/asteroid/DPTNet_Libri1Mix_enhsignle_16k.pth
  wandb: True
  qat: True
  kd_lambda: 0.0
  weight_quant: True
  act_quant: True
  in_quant: False
  out_quant: False
  seed: 0
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.0
scheduler:
  steps_per_epoch: 10000
  d_model: 64
# Data config
data:
  # sep_clean, enh_single
  task: enh_single
  train_dir: data/wav16k/min/train-360
  valid_dir: data/wav16k/min/dev
  sample_rate: 16000
  n_src: 1
  segment: 3

